name: q_flutter_starter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^7.0.0
  cupertino_icons: ^1.0.2
  firebase_analytics: ^8.0.0
  firebase_core: ^1.0.3
  firebase_crashlytics: ^2.0.0
  injectable: ^1.2.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_flavorizr: 1.0.11
  lint: ^1.5.3

flutter:
  uses-material-design: true

flavorizr:
  app:
    android:
      flavorDimensions: "app"
    ios: null

  flavors:
    dev:
      app:
        name: "${APP_NAME} Dev"
      android:
        applicationId: "${ID_DEV}"
        firebase:
          config: ".firebase/android/dev/google-services.json"

      ios:
        bundleId: "${ID_DEV}"
        firebase:
          config: ".firebase/ios/dev/GoogleService-Info.plist"

    staging:
      app:
        name: "${APP_NAME} Staging"
      android:
        applicationId: "${ID_STAGING}"
        firebase:
          config: ".firebase/android/staging/google-services.json"
      ios:
        bundleId: "${ID_STAGING}"
        firebase:
          config: ".firebase/ios/staging/GoogleService-Info.plist"

    prod:
      app:
        name: "${APP_NAME}"
      android:
        applicationId: "${ID_PROD}"
        firebase:
          config: ".firebase/android/prod/google-services.json"
      ios:
        bundleId: "${ID_PROD}"
        firebase:
          config: ".firebase/ios/prod/GoogleService-Info.plist"
